### ISSUE TITLE
Duplicate named routes after scaffold generation

### ISSUE THREAD

**Issue by SidneySaints** [andrewdwallo/filament-companies#10]
HI,

on a fresh laravel/filament/filament-companies installation I'm getting this error by running ```php artisan route:clear```

**Unable to prepare route [admin/create] for serialization. Another route has already been assigned name [filament.pages.create].**

After some debugging I figured out this conflict depends on duplicate pages that exists in filament-companies package and my project after running ```php artisan filament-companies:install filament --companies```

**Comment by andrewdwallo** [comment]
I'm confused because I do not have that error after running this command after a fresh install... Have you changed the slugs of any routes?

**Comment by andrewdwallo** [comment]
or the slugs inside the Filament Pages?

**Comment by SidneySaints** [comment]
nope, I just install filament and filament-companies on ja fresh laravel project. no configs changed

**Comment by andrewdwallo** [comment]
can you send me the exact message of the issue?

**Comment by SidneySaints** [comment]
but if slugs was changed in App\Filament\Pages\Company\**.php and App\Filament\Pages\User\**.php the error disappears

**Comment by SidneySaints** [comment]
``` 
 Unable to prepare route [create] for serialization. Another route has already been assigned name [filament.pages.create].

  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:247
    243▕             $route->name($this->generateRouteName());
    244▕ 
    245▕             $this->add($route);
    246▕         } elseif (! is_null($symfonyRoutes->get($name))) {
  ➜ 247▕             throw new LogicException("Unable to prepare route [{$route->uri}] for serialization. Another route has already been assigned name [{$name}].");
    248▕         }
    249▕ 
    250▕         $symfonyRoutes->add($route->getName(), $route->toSymfonyRoute());
    251▕ 

      +35 vendor frames 
  36  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
``` 
sorry for this crap formatting

**Comment by andrewdwallo** [comment]
yes that is what I was talking about... The slugs represent the route, you must keep those the same as first install

**Comment by andrewdwallo** [comment]
in App\Filament\Pages\Companies\Create the slug should be 
`protected static ?string $slug = 'create';`

**Comment by SidneySaints** [comment]
```php
class Create extends Page
{
    protected static ?string $title = 'Create Company';

    protected static ?string $slug = 'create';

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.companies.create';

    protected static bool $shouldRegisterNavigation = false;
}
```
The conflict above appears.

for example:
```php
class Create extends Page
{
    protected static ?string $title = 'Create Company';

    protected static ?string $slug = 'company-create';

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.companies.create';

    protected static bool $shouldRegisterNavigation = false;
}
```

The conflict above disappears

**Comment by SidneySaints** [comment]
oh sorry. try running ```php artisan optimize```

**Comment by andrewdwallo** [comment]
I usually run php artisan optimize all the time, but I did run php artisan route:clear and had no issues so I am not sure what that was about and changing the slug to 'company-create' would just make the route unable to be found...  The slug represents the name of the file, which is create.php in the resources/views/filament/pages/companies/ directory.. you can't change the slug no matter what.

**Comment by SidneySaints** [comment]
so I'm confused I getting this error and you didn't

**Comment by andrewdwallo** [comment]
No I didn't maybe try reinstalling and see what happens

**Comment by SidneySaints** [comment]
I did already a reinstall. because i thought the error depends on something else. I'm on a fresh laravel installation with filament and your package. Did you try a fresh install :-)?

**Comment by andrewdwallo** [comment]
Haha, yes I try a fresh install every time I update the package... Is the issue resolved for you?

**Comment by SidneySaints** [comment]
No, but it seems you cant help. So I will try debugging. If I'm right, filament will generate automatically the routes of all pages, right? So, this will conflict with your web.php which is provided by you package, right? (If not, maybe you can explain it briefly) Sorry im trying to figured out whats going wrong, maybe someone else get this error and I think thats a great package  :-)

**Comment by andrewdwallo** [comment]
Thank you for the complement of the package.. I am working on updating the web.php file and fixing all of these things within the next few days or earlier. The web.php file has controllers that are connected to the filament page views, but this may not be necessary and I will see. You are welcome to make a PR to fix these issues if you want to help...

**Comment by SidneySaints** [comment]
In web.php line 29,34,40,42 this route names will conflict with filament auto generated routes. Are these needed at all? If yes, how can I access them?

**Comment by andrewdwallo** [comment]
You don't need to change them or mess with them in any way.
