### ISSUE TITLE
Ability to change naming

### ISSUE THREAD

**Issue by dominikfomicz** [andrewdwallo/filament-companies#101]
For example instead of /companies/1 we could have a like teams or ogranization - would be helpful :)

**Comment by andrewdwallo** [comment]
Thanks for your suggestion! This is more of a feature request than a bug/issue. Could you please post it in the 'Discussions' section of the repo? It’s the best place for ideas and enhancements. Closing this as it is not relevant to an issue/bug with the package itself. Thanks!
