### ISSUE TITLE
Adding users to company

### ISSUE THREAD

**Issue by dreamfast** [andrewdwallo/filament-companies#102]
Hi, thanks for making this plugin!

I mainly have three panels, admin, company (url as /dashboard) and user.

So far everything seems to be working okay, however when testing adding new users to the company in company settings I have an issue with them logging in and being able to see the company or user panel.

The invitation sends fine and I can see them in pending invitations.

- The invitation email links to `/dashboard/register`
- After the invited user has made an account there is an error, it will try to redirect to dashboard/new
- `Missing required parameter for [Route: filament.company.pages.dashboard] [URI: dashboard/{tenant}] [Missing parameter: tenant].`
- From what I can see the "tenant" is null, and is trying to make a new company.
- Ideally they would not create a new company, and instead be directed to the company dashboard they were invited to.

Is the company ID supposed to be assigned on account creation? Or somehow the `company_user` is supposed to have the user ID associated to Company ID? I've reviewed again the setup guide however could have overlooked something simple.

**Comment by andrewdwallo** [comment]
By default, every user must create a company.

**Comment by dreamfast** [comment]
@andrewdwallo Thanks

**Comment by andrewdwallo** [comment]
Sorry. This is just the default behavior. You can change this in your application though by overriding the logic in the Company creation page upon other things. You can look on google by searching for the topic with Jetstream. The same thing would apply here essentially.
