### ISSUE TITLE
Error thrown: Route [filament.company.oauth.redirect] not defined when changing company panel ID

### ISSUE THREAD

**Issue by tristan-thar** [andrewdwallo/filament-companies#105]
**Description:**
When modifying the panel ID in the `FilamentCompaniesServiceProvider`, a route-related exception occurs upon accessing the user profile. The issue stems from the hard-coded route reference in the `resources/views/profile/connected-accounts-from.blade.php` file (line 50), specifically pointing to `filament.company.oauth.redirect`.

**Reproduction Steps:**

1. Navigate to `FilamentCompaniesServiceProvider`.

2. Modify the panel ID within the panel method.

```
public function panel(Panel $panel): Panel
{
    return $panel
        ->id('custom')
        ->path('custom')
        ->homeUrl(static fn (): string => url(Pages\Dashboard::getUrl(panel: 'custom', tenant: Auth::user()?->personalCompany())))
        // ... other configurations
}
```

3. Attempt to access the user profile.

**Expected Behavior:**
Routes in `routes/web.php` are dynamically generated based on the panel ID. Therefore, the correct route in this case should be `filament.custom.oauth.redirect` instead of the hard-coded `filament.company.oauth.redirect` in `connected-accounts-from.blade.php`.

**File Reference:**
Affected File: `resources/views/profile/connected-accounts-from.blade.php`
Line Number: 50
Proposed Solution:
Update the route reference in `connected-accounts-from.blade.php` to use the dynamically generated route based on the panel ID, i.e., `filament.custom.oauth.redirect`.

**Comment by andrewdwallo** [comment]
Okay thanks. Will fix soon and come back to you.

**Comment by andrewdwallo** [comment]
@heureka-dev Fixed in latest release. Please update and let me know.

**Comment by tristan-thar** [comment]
Thanks a lot for the swift response @andrewdwallo. This fixed it.
