### ISSUE TITLE
userMenuItems

### ISSUE THREAD

**Issue by vargaatish** [andrewdwallo/filament-companies#106]
Hi, thanks for this plugin!

After a clearly fresh Laravel, Filament install got this error:
Route [filament.admin.pages.profile] not defined.

It causes by `/app/Providers/FilamentCompaniesServiceProvider.php`

This part from line 92:
`->userMenuItems([
                'profile' => MenuItem::make()
                    ->label('Profile')
                    ->icon('heroicon-o-user-circle')
                    ->url(static fn () => route(Profile::getRouteName(panel: 'admin'))),
            ])`

**Comment by andrewdwallo** [comment]
What is the panel ID where your profile page will be?

**Comment by vargaatish** [comment]
It's just the default: 'admin'

```
class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->id('admin')
            ->path('admin')
```

**Comment by andrewdwallo** [comment]
Have you followed all the instructions in the documentation before posting an issue? Did you register your profile page in the admin panel?

**Comment by vargaatish** [comment]
Yes, but missed this part, thanks for clarifying.

For newbies like me, here you can register it:

```
use Wallo\FilamentCompanies\Pages\User\PersonalAccessTokens;
use Wallo\FilamentCompanies\Pages\User\Profile;

public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->pages([
            Profile::class,
            PersonalAccessTokens::class,
        ])
}
```

**Comment by andrewdwallo** [comment]
It shows how to register it here. Anyways, glad you found the fix. 👍
![image](https://github.com/andrewdwallo/filament-companies/assets/104294090/f66b0efa-1769-4d21-91db-213571451ac5)
