### ISSUE TITLE
Company Settings

### ISSUE THREAD

**Issue by vargaatish** [andrewdwallo/filament-companies#107]
After a clearly fresh Laravel, Filament install, saving Company Name, error will be shown:
Livewire  \  Exceptions
 
ComponentNotFoundException
PHP 8.2.13
Laravel 10.34.2

Unable to find component: [wallo.filament-companies.http.livewire.update-company-name-form]

Same behaviour on saving user to company:
Unable to find component: [wallo.filament-companies.http.livewire.company-employee-manager]

**Comment by andrewdwallo** [comment]
@vargaatish Did you figure this out?

**Comment by vargaatish** [comment]
Not yet, if you have an idea, it would be great

**Comment by andrewdwallo** [comment]
Okay I just noticed this error as well. I will look into it, thanks.

**Comment by andrewdwallo** [comment]
@vargaatish Please update to the latest release! Let me know if all good.

**Comment by vargaatish** [comment]
@andrewdwallo Now it works well, thank you.
