### ISSUE TITLE
cant install package 

### ISSUE THREAD

**Issue by Fik21-i** [andrewdwallo/filament-companies#110]
Problem 1
    - andrewdwallo/filament-companies[dev-main, v1.0.0, ..., 1.x-dev, v2.0.0, ..., 2.x-dev] require filament/filament ^2.16 -> found filament/filament[v2.16.0, ..., 2.x-dev] but it conflicts with your root composer.json require (^3.0-dev).
    - andrewdwallo/filament-companies[dev-dependabot/github_actions/stefanzweifel/git-auto-commit-action-5, v3.0.0, ..., 3.x-dev] require illuminate/support ^10.0 -> found illuminate/support[v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires andrewdwallo/filament-companies * -> satisfiable by andrewdwallo/filament-companies[dev-dependabot/github_actions/stefanzweifel/git-auto-commit-action-5, dev-main, v1.0.0, ..., 1.x-dev, v2.0.0, ..., 2.x-dev, v3.0.0, ..., 3.x-dev].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require andrewdwallo/filament-companies:*" to figure out if any version is installable, or "composer require andrewdwallo/filament-companies:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

hi , im still new in filament . im trying to install your package but seems not working because your package just support for only version 2. am i right ?

**Comment by andrewdwallo** [comment]
No, currently it supports v3 of Filament.

**Comment by andrewdwallo** [comment]
Can you show me your `composer.json` file?

**Comment by Fik21-i** [comment]
"name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "anaseqal/nova-sidebar-icons": "^0.0.3",
        "blade-ui-kit/blade-heroicons": "^2.1",
        "comodolab/nova-help": "^0.5.0",
        "devpartners/auditable-log": "^2.0",
        "digital-creative/resource-navigation-tab": "^2.1",
        "ebess/advanced-nova-media-library": "^4.1",
        "eminiarts/nova-tabs": "^2.2",
        "filament/filament": "^3.0-dev",
        "filament/spatie-laravel-media-library-plugin": "^3.0-stable",
        "guzzlehttp/guzzle": "^7.2",
        "habibtalib/novatoolpermissions": "dev-master",
        "jantinnerezo/livewire-alert": "^2.2",
        "kabbouchi/nova-impersonate": "^2.0",
        "laravel/framework": "^9.19",
        "laravel/nova": "4.23",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7",
        "livewire/livewire": "^2.12",
        "maatwebsite/excel": "^3.1",
        "maatwebsite/laravel-nova-excel": "^1.3",
        "magdicom/nova-visible-password": "^1.0",
        "markrogoyski/math-php": "^2.8",
        "ngiraud/nova-header-field": "^1.0",
        "norman-huth/nova-menu": "^1.0",
        "norman-huth/nova-resource-card": "^1.0",
        "oriondevelops/nova-greeter": "^0.0.1",
        "outl1ne/nova-detached-filters": "^2.0",
        "owen-it/laravel-auditing": "^13.0",
        "phpoffice/phpspreadsheet": "^1.29",
        "phpoffice/phpword": "^1.0",
        "psr/simple-cache": "^2.0",
        "scalexy/royal-theme": "^0.9.3",
        "sentry/sentry-laravel": "^3.4",
        "shuvroroy/nova-tabs": "^1.1",
        "timothyasp/nova-badge-field": "^2.0.0",
        "trin4ik/nova-switcher": "^0.3.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.9",
        "fakerphp/faker": "^1.9.1",
        "filament/upgrade": "^3.0-stable",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    
    here is my composer.json

**Comment by andrewdwallo** [comment]
Why are you using Nova with Filament?
Anyways, change:
```
"filament/filament": "^3.0-dev",
```

to
```
"filament/filament": "^3.0",
```

And see if that changes anything.

**Comment by andrewdwallo** [comment]
Filament requires Laravel 10.x

**Comment by andrewdwallo** [comment]
Closing due to nothing wrong with my package. I can continue to help but this would be a better question for Filament discord.
