### ISSUE TITLE
Missing required parameter for [Route: filament.company.pages.dashboard] [URI: company/{tenant}] [Missing parameter: tenant]

### ISSUE THREAD

**Issue by tdisit** [andrewdwallo/filament-companies#111]
I'm getting this error. I really don't know where I'm going wrong.

**Missing required parameter for [Route: filament.company.pages.dashboard] [URI: company/{tenant}] [Missing parameter: tenant].**

![2023-12-11 (1)](https://github.com/andrewdwallo/filament-companies/assets/95700404/da6a017f-3e9a-4f9d-8f7a-fc1d6c1bc140)

**Comment by mkamran8** [comment]
Hi @tdisit, Did you figure this out? I am getting the same error.

**Comment by a21ns1g4ts** [comment]
I’m not sure, but I think this won’t work well when you’re under a tenant scope, since the interaction with the API always redirects you to the Profile Page, and the implementation doesn’t account for whether you need to pass a tenant ID.

**Comment by andrewdwallo** [comment]
@a21ns1g4ts You can pass a tenant id..

**Comment by a21ns1g4ts** [comment]
@andrewdwallo It seems this issue isn't related to this package. The tenant parameter is likely null for some other reason within userMenuItems.
