### ISSUE TITLE
 Error thrown: Route [filament.wedding.wedding-invitations.accept] not defined when adding user with custom panel ID

### ISSUE THREAD

**Issue by veceraj** [andrewdwallo/filament-companies#118]
### Description:
When adding a user in the settings and having a custom panel ID the user is added but an exception is thrown when trying to send an email: `Mail::to($email)->send(new CompanyInvitation($invitation));`.

Could be related to: https://github.com/andrewdwallo/filament-companies/issues/105

### Reproduction Steps:
1. Navigate to `FilamentCompaniesServiceProvider`.
2. Modify the panel ID
``` php
public function panel(Panel $panel): Panel
{
    return $panel
        ->id('custom')
        ->path('custom')
        ->homeUrl(static fn (): string => url(Pages\Dashboard::getUrl(panel: 'custom', tenant: Auth::user()?->personalCompany())))
        // ... other configurations
}
```
3. Navigate to settings and attempt to invite new user

### Expected Behavior:
The user is invited and email is sent.

**Comment by andrewdwallo** [comment]
@veceraj Hey, thank you for reporting this. This should be fixed in the latest release. Please update and let me know. Thanks!
