### ISSUE TITLE
Current company name problem after the first registration

### ISSUE THREAD

**Issue by rizaergun** [andrewdwallo/filament-companies#13]
Hi,

I am getting the current company name null problem after the first registration.

Attempt to read property "name" on null

resources/ views / navigation-menu.blade.php:9

```
<div class="flex justify-end">

    @if (Wallo\FilamentCompanies\FilamentCompanies::hasCompanyFeatures())

        <x-filament::dropdown placement="bottom-end">

            <x-slot name="trigger" class="ml-4">

                <button @class([

                    'inline-flex items-center px-3 py-2 border border-transparent text-sm text-gray-800 hover:text-primary-500 leading-4 font-medium rounded-md bg-white hover:bg-gray-50 focus:outline-none focus:bg-gray-50 active:bg-gray-50 transition

                    'dark:bg-gray-800 dark:hover:bg-gray-700 dark:border-white dark:hover:border-primary-400 dark:text-white dark:hover:text-primary-400' => config('filament.dark_mode'),

                ])>

                    **{{ Auth::user()->currentCompany->name }}**

                    <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">

                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 15L12 18.75 15.75 15m-7.5-6L12 5.25 15.75 9" />

                    </svg>

                </button>

            </x-slot>
```

**Comment by andrewdwallo** [comment]
Have you changed anything after installation? I need more information regarding your application to determine if this is an issue with the package or just your application...

**Comment by andrewdwallo** [comment]
Make sure that all FilamentCompany features are implemented in your User Model.

e.g.

```
use HasApiTokens;
use HasFactory;
use HasProfilePhoto;
use HasCompanies;
use Notifiable;
use TwoFactorAuthenticatable;
```

**Comment by rizaergun** [comment]
Hi @andrewdwallo ,

Yes, I've created a new laravel project and then tried on that it works well. My project wasn't from scratch I just have a few filament things I guess it was a problem. I couldn't find the problem yet but it works fine on the new laravel project.

**Comment by andrewdwallo** [comment]
Well I am not sure how to fix it then but I am about to make a huge update so maybe what I do will fix it so stay tuned!

**Comment by rizaergun** [comment]
Great news! Are you working on the refractor branch?

**Comment by andrewdwallo** [comment]
Yes I am, what you see currently in the branch is outdated tho, I have done a lot of changes since then but just haven't made the pull request yet...
