### ISSUE TITLE
create:filament-company-user is not showing with Laravel 11

### ISSUE THREAD

**Issue by ciebrant** [andrewdwallo/filament-companies#131]
Hello,

With a fresh install of Laravel (v11), everything is looking well, but the artisan command for creating a user is not showing up.
Maybe there is a quick fix?

Gr.
Virgil

**Comment by andrewdwallo** [comment]
This command is no longer available. It is easy to register a user manually. I don't want to maintain this command, sorry. See the [UPGRADE.md](https://github.com/andrewdwallo/filament-companies/blob/4.x/UPGRADE.md) file. This is mentioned there.

**Comment by mariomka** [comment]
It seems that [the Filament plugin page](https://filamentphp.com/plugins/andrew-wallo-companies#translations-and-views) isn't updated, and it still talks about this command.

**Comment by geraistec** [comment]
The same thing, still.
