### ISSUE TITLE
new panel

### ISSUE THREAD

**Issue by rasul-chopurov** [andrewdwallo/filament-companies#140]
i am make new panel "company"

and added

```
            ->userMenuItems([
                'profile' => MenuItem::make()
                    ->label('Profile')
                    ->icon('heroicon-o-user-circle')
                    ->url(static fn () => url(Profile::getUrl())),
                MenuItem::make()
                    ->label('Company')
                    ->icon('heroicon-o-building-office')
                    ->url(static fn () => url(Pages\Dashboard::getUrl(panel: 'company', tenant: Auth::user()->personalCompany()))),
            ])
            ->navigationItems([
                NavigationItem::make('Personal Access Tokens')
                    ->label(static fn (): string => __('filament-companies::default.navigation.links.tokens'))
                    ->icon('heroicon-o-key')
                    ->url(static fn () => url(PersonalAccessTokens::getUrl())),
            ])
```

and in "FilamentCompaniesServiceProvider"

change panel name to company

why next step "Route [filament.company.pages.profile] not defined." why?

**Comment by rasul-chopurov** [comment]
error    ->userMenuItems([
                'profile' => MenuItem::make()
                    ->label('Profile')
                    ->icon('heroicon-o-user-circle')
                    ->url(static fn () => route(Profile::getRouteName(panel: 'company'))),
            ])

**Comment by andrewdwallo** [comment]
This is because the user profile menu items should be defined in the User panel, not the company panel. You also need to make sure you register the Pages.
