### ISSUE TITLE
Custom Socialite providers 

### ISSUE THREAD

**Issue by mariomka** [andrewdwallo/filament-companies#149]
Right now, only default providers are supported, but there are a lot of providers at https://socialiteproviders.com, and you can also implement a custom provider. Is there any way to support other or custom providers? It seems coupled to the `Provider` enum that can't be extended.

**Comment by andrewdwallo** [comment]
This is a feature request, not an issue. Move this to a [Discussion](https://github.com/andrewdwallo/filament-companies/discussions/new?category=feature-requests).
