### ISSUE TITLE
Call to a member function map() on null

### ISSUE THREAD

**Issue by pebarradasaero** [andrewdwallo/filament-companies#150]
when access to user profile page:

![image](https://github.com/user-attachments/assets/ac0437d8-40ff-48ff-aa47-dcea74b6b50f)

**Comment by andrewdwallo** [comment]
Are you using only the Base package?

**Comment by andrewdwallo** [comment]
Laravel would return an empty collection even if the connectedAccounts relationship was null. I just tested this and I have no issues. It must be specific to your environment.

**Comment by pebarradasaero** [comment]
> Are you using only the Base package?

yes! a clean install of laravel + filamentphp and your package
