### ISSUE TITLE
Auto create company on User Signup

### ISSUE THREAD

**Issue by JakeOcean** [andrewdwallo/filament-companies#151]
How do I auto create a Company when a User Joins?  Currently I am redirected to the form to add a Company name, but I see in `CreateNewUser` that a new Company should be auto created with `$this->createCompany($user)` -- is there additional setup required for this fire?

In my `FilamentCompaniesServiceProvider` I do have `FilamentCompanies::createUsersUsing(CreateNewUser::class);` but adding a Log there seems as if it isnt being used

**Comment by andrewdwallo** [comment]
You are going to have to create a new Register page, extend mine (or don't) and force the creation of a company and login the user by regenerating the session.

**Comment by andrewdwallo** [comment]
Socialite does this by default. You can have a look at this file for help: https://github.com/andrewdwallo/filament-companies/blob/4.x/src/Http/Controllers/OAuthController.php
