### ISSUE TITLE
Route [filament.app.tenant.profile] not defined.

### ISSUE THREAD

**Issue by emildayan** [andrewdwallo/filament-companies#158]
Hi,

Brand new Laravel+Livewire+Filament install, latest version.

Route [filament.app.tenant.profile] not defined.

Re-done the process several times - can't get past this. Following your docs to the t.
What am I missing?

Thanks,

**Comment by andrewdwallo** [comment]
Did you register the Profile page in the panel? Have you looked at all other similar issues and discussions?

**Comment by emildayan** [comment]
> Did you register the Profile page in the panel? Have you looked at all other similar issues and discussions?

Yes, profile registered, looked through all similar issues but none of them seem to solve it, discussion just ends up being closed. 

For those that mentioned some sort of solution I've attempted their solution without luck.

Something just feels 'off' as even the register is not triggered properly (no company is being created at the same time as a user).

**Comment by emildayan** [comment]
**With Profile::class registered in pages:**
php artisan route:list
admin/{tenant}/profile > filament.admin.**pages**.profile › Wallo\FilamentCompanies › Profile

**Without:**
php artisan route:list
admin/{tenant}/profile > filament.admin.**tenant**.profile › Wallo\FilamentCompanies › CompanySettings

**Comment by andrewdwallo** [comment]
Show me the code of both of your panel providers.

**Comment by andrewdwallo** [comment]
@emildayan I created an example app/demo for you to look at so you can know how to correctly set up your app. You can compare with what you have now: https://github.com/andrewdwallo/filament-companies-example-app

**Comment by emildayan** [comment]
Thanks for the demo app - up and running now, much appreciated.

**Comment by andrewdwallo** [comment]
@emildayan Great!
