### ISSUE TITLE
Call to undefined function hasVerifiedEmail()

### ISSUE THREAD

**Issue by sunxyw** [andrewdwallo/filament-companies#25]
https://github.com/andrewdwallo/filament-companies/blob/55bd9a26a2ad7cebfd21a56e364652d3be4ae317/resources/views/profile/update-profile-information-form.blade.php#L74-L75

should be `$this->user->hasVerifiedEmail()`?

**Comment by andrewdwallo** [comment]
Just saw this and just implemented a large update that fixed this as well, thank you!
