### ISSUE TITLE
Missing return in UpdateProfileInformationForm::updateProfileInformation

### ISSUE THREAD

**Issue by sunxyw** [andrewdwallo/filament-companies#35]
I think it's a bug? Occurs when attempting to update the user name.
`Wallo\FilamentCompanies\Http\Livewire\UpdateProfileInformationForm::updateProfileInformation(): Return value must be of type Livewire\Redirector|Illuminate\Http\RedirectResponse, none returned`
https://github.com/andrewdwallo/filament-companies/blob/1.x/src/Http/Livewire/UpdateProfileInformationForm.php#L58-L80

**Comment by andrewdwallo** [comment]
Fixed in latest release, please update and let me know!

**Comment by sunxyw** [comment]
Yes, it works fine now. 👍
