### ISSUE TITLE
Additional Roles?

### ISSUE THREAD

**Issue by bluecraank** [andrewdwallo/filament-companies#48]
Hello,

maybe i didnt see that but how can i add roles / permissions?

**Comment by andrewdwallo** [comment]
Roles can be added in `app/Providers/FilamentCompaniesServiceProvider.php`
```
/**
     * Configure the roles and permissions that are available within the application.
     */
    protected function configurePermissions(): void
    {
        FilamentCompanies::defaultApiTokenPermissions(['read']);

        FilamentCompanies::role('admin', 'Administrator', [  <-- role
            'create', <-- Permissions
            'read',
            'update',
            'delete',
        ])->description('Administrator users can perform any action.');

        FilamentCompanies::role('editor', 'Editor', [
            'read',
            'create',
            'update',
        ])->description('Editor users have the ability to read, create, and update.');
    }
```

Each added role needs permissions, and each added permission needs to belong to a role. Most of the documentation in Laravel Jetstream applies for this plugin as well. Or should I say that all of Jetstream documentation applies for this plugin (naming is different), except for the case with socialite.

**Comment by andrewdwallo** [comment]
If you have any further questions please do not post here as this is for issues, but as for questions I would encourage to join the Filament Discord, my plugins channel can be found there.

**Comment by bluecraank** [comment]
Thanks and sorry!

**Comment by andrewdwallo** [comment]
Its okay, just wanted to mention it!
