### ISSUE TITLE
Navigation error on user with zero companies (Attempt to read property "name" on null)

### ISSUE THREAD

**Issue by LuanHimmlisch** [andrewdwallo/filament-companies#69]
![image](https://github.com/andrewdwallo/filament-companies/assets/46875694/5a44cc58-a164-4013-b8a8-bc848f98159b)
![image](https://github.com/andrewdwallo/filament-companies/assets/46875694/06addbf2-5443-449e-ba11-44cf68122d43)

A middleware to redirect users to create a company would be appreciated.

Example:

```php
class HasCompany
{
    const PATH = 'admin/companies/create';

    public function handle(Request $request, Closure $next)
    {
        /** @var User */
        $user = auth()->user();
        if (
            !$user->ownedCompanies()->exists() &&
            !$user->companies()->exists() &&
            !$request->is(self::PATH)
        ) {
            return redirect(self::PATH);
        }
        return $next($request);
    }
}
```

**Comment by andrewdwallo** [comment]
The package wasn't designed to handle users with zero companies.

**Comment by LuanHimmlisch** [comment]
@andrewdwallo the package is meant to create the first company outside the admin panel, then? 
It's not much of a difference, the only thing that would have to change is hiding the company menu when there's no existing company and redirect to create one with the already made form. 

It would give the ease to developers of choosing to not create a totally new form when there's already one created, and prevents an ugly exception that happens just on installation.

**Comment by LuanHimmlisch** [comment]
@andrewdwallo saw the fortify event `CreateNewUser`... It would be nice to document that this package will throw an error if you create a user manually with `make:filament-user`. The other solution would be to move the `createCompany` to a `created` event on a `bootHasCompanies`, although I guess that would go against the "Actions" approach

**Comment by andrewdwallo** [comment]
@LuanHimmlisch I do not see any reason for implementing the `make:filament-user` command for this package since there is a registration page. You can also do the same thing using Factories, Seeders, etc., so yeah, I suppose I will document that the command will throw an error. Please don't post any more issues unless something isn't working when it was intended to work, it doesn't look nice when potential users see it. Only 1 or 2 out of the 8 issues listed for this package have been actual issues, the rest were just general questions or feature requests. Please make a discussion post or ask me in discord if you have questions or feature requests, please and thank you!

**Comment by LuanHimmlisch** [comment]
@andrewdwallo of course, but at least this issue is more than justifiable, sorry if it troubles you. A package should work on the normal workflow where it's expected to be used, on Filament, the documented way to create a new user is by using its command, if a package differs from the workflow normally is documented. Thanks to you :handshake:

**Comment by LuanHimmlisch** [comment]
@andrewdwallo A package is normally expected to work in the ecosystem it's for. Filament suggests seeding the first user with its command on a **fresh installation**, something specifically mentioned this package is made for. If it differs from the normal workflow, a package normally documents it. Sorry for the previous issue, but this one does have grounds.  Thanks to you, and sorry for the troubles :handshake:

**Comment by andrewdwallo** [comment]
I was talking about the 2 issues you posted, not the `make:filament-user` command. This is a free package, and you are welcome to contribute all you want. The Authentication system built with this package is very much different from the filament base installation, so no not everything should and will apply. I will make note of it in the documentation and perhaps I may integrate it, but no promises.

**Comment by andrewdwallo** [comment]
It's fine. I just thought I should mention it. I will see what I can do regarding this since the Authentication system for this package is very much different from the base Filament installation.

**Comment by andrewdwallo** [comment]
The reason why it does not work is because the route for login for Filament base installation is `filament.auth.login`. This packages route is different. Also it is because this package requires that every user have a company.

**Comment by andrewdwallo** [comment]
@LuanHimmlisch https://github.com/andrewdwallo/filament-companies/releases/tag/v2.0.5
