### ISSUE TITLE
`currentCompany` null on deletion of previous company

### ISSUE THREAD

**Issue by LuanHimmlisch** [andrewdwallo/filament-companies#70]
On deleting a company, the `current_company_id` keeps the id of the deleted company.

I resolved adding a Middleware to change it to another company id.
```php
if (is_null($user->currentCompany)) {
        $user->current_company_id = $user->ownedCompanies()->firstOr(fn () => $user->companies()->first())->id;
        $user->save();
        return redirect()->intended($request->path());
}
```

There should be an event on deleting to check if that's the current_company_id, and if it is, it should be changed.

**Comment by andrewdwallo** [comment]
I'm confused on what you are talking about. "On deleting a company, the `current_company_id` keeps the id of the deleted company." What does that even mean? Once a company is deleted it is removed from the database.

**Comment by andrewdwallo** [comment]
And you can't alter the current company id by changing it to another company ID. That is not correct and you shouldn't do that.

**Comment by andrewdwallo** [comment]
Please look here:
https://github.com/andrewdwallo/filament-companies/blob/2.x/src/Company.php

**Comment by LuanHimmlisch** [comment]
@andrewdwallo yeah, sorry. I added a soft delete to the company, meaning the column isn't set to null on cascade.
