### ISSUE TITLE
  Undefined property: Wallo\FilamentCompanies\Console\InstallCommand::$components

### ISSUE THREAD

**Issue by papipsycho** [andrewdwallo/filament-companies#73]
Hello,

i where faced to this issue will i wanted to setup:

/usr/bin/php8.1/php artisan filament-companies:install filament --companies
Migration created successfully!
Copied Directory [/vendor/laravel/sanctum/database/migrations] To [/database/migrations]
Copied File [/vendor/laravel/sanctum/config/sanctum.php] To [/config/sanctum.php]
Publishing complete.

   ErrorException

  Undefined property: Wallo\FilamentCompanies\Console\InstallCommand::$components

  at vendor/andrewdwallo/filament-companies/src/Console/InstallCommand.php:190
    186▕             $this->installFilamentCompanyStack();
    187▕         }
    188▕
    189▕         $this->line('');
  ➜ 190▕         $this->components->info('Filament scaffolding installed successfully.');
    191▕
    192▕         return true;
    193▕     }
    194▕

**Comment by andrewdwallo** [comment]
Did you manually copy over components and files before installation?

**Comment by papipsycho** [comment]
Nop, i didn't copy manally any components, 

Btw to fix i just comment this line.

**Comment by andrewdwallo** [comment]
@papipsycho Comment what line? Is your issue fixed? I have not had this error.

**Comment by papipsycho** [comment]
yes i commented this line, 

➜ 190▕ $this->components->info('Filament scaffolding installed successfully.');

and it was OK.
