### ISSUE TITLE
Additional fields ?

### ISSUE THREAD

**Issue by papipsycho** [andrewdwallo/filament-companies#74]
Hello Guys, 

I check the documentation but i didn't found any explaination for how to add new fields into the  add/edit page of the company ?

Best

**Comment by andrewdwallo** [comment]
@papipsycho This link should help: https://laraveldaily.com/post/laravel-jetstream-add-field-to-profile-form
The package is based on Laravel Jetstream and mostly all documentation for Laravel Jetstream covers what can be done in this package as well. If you feel like I need to add specifics to the documentation on this please let me know and I will. Thanks!

**Comment by papipsycho** [comment]
hey @andrewdwallo thanks for your anwser, the problem is the view, there is no way currently to publish the view (for adding my fields) ?

**Comment by andrewdwallo** [comment]
Hey @papipsycho, I understand your concern. To edit or update any files, you need to first copy them from the `vendor` directory to the `resources` directory in your current application. Initially, Filament didn't recommend adding a command to publish the views, as it would publish all views—including those you may not want to edit.

Also, once these views have been published, they're not able to receive automatic updates from any future package releases. This situation could potentially lead to errors or breaking changes in your application. Thus, it's recommended to selectively transfer only the files you plan on modifying or updating to keep potential errors to a minimum. However, it's important to note that manual updates are still a viable option to prevent these issues after any new release.

With the imminent release of Filament V3, significant alterations to these views are expected to be minimal. For convenience, I'm considering adding the command. I hope this clears things up. Does this solution address your question?

**Comment by andrewdwallo** [comment]
@papipsycho https://github.com/andrewdwallo/filament-companies/releases/tag/v2.0.6 The command to publish views was added to the latest release. Please update and let me know if you have any further questions, thanks!

**Comment by papipsycho** [comment]
thanks a lot mate
