### ISSUE TITLE
Migration v3

### ISSUE THREAD

**Issue by papipsycho** [andrewdwallo/filament-companies#77]
Hey, 

I start migrating this  package thought v3, still not finish but i'm in progress,

did you start something or not yet ?

**Comment by andrewdwallo** [comment]
Im trying to but currently, Filament v3 Tenancy has too many bugs. Also, this isn't an issue, this is a feature request. If you would like to talk more about it please start a discussion for this package or talk about it in my packages channel in Filament Discord.
