### ISSUE TITLE
Method Filament\Panel::getDomains does not exist.

### ISSUE THREAD

**Issue by syed-reza98** [andrewdwallo/filament-companies#99]
@andrewdwallo 
For command: php artisan filament-companies:install. I used the Base Package.

The error I'm facing after running migration command is: 

BadMethodCallException 

  Method Filament\Panel::getDomains does not exist.

  at vendor\filament\support\src\Concerns\Macroable.php:72
     68▕     {
     69▕         $macro = static::getMacro($method);
     70▕
     71▕         if ($macro === null) {
  ➜  72▕             throw new BadMethodCallException(sprintf(
     73▕                 'Method %s::%s does not exist.',
     74▕                 static::class,
     75▕                 $method,
     76▕             ));

  i   Bad Method Call: Did you mean Filament\Panel::getDomain() ?

  1   vendor\andrewdwallo\filament-companies\routes\web.php:22
      Filament\Support\Components\Component::__call("getDomains", [])

  2   vendor\laravel\framework\src\Illuminate\Routing\Router.php:502
      Illuminate\Support\ServiceProvider::{closure}(Object(Illuminate\Routing\Router))

**Comment by andrewdwallo** [comment]
Hey. Did you install filament before installing my package?

**Comment by syed-reza98** [comment]
> Hey. Did you install filament before installing my package?

Yes

**Comment by syed-reza98** [comment]
> Hey. Did you install filament before installing my package?

@andrewdwallo 
Yes I have installed filament properly by running 

composer require filament/filament:"^3.0-stable" -W
 
php artisan filament:install --panels

**Comment by andrewdwallo** [comment]
I just installed the base package as well to see if anything is wrong, and everything worked just fine for me. No issues. So, I am unsure why it would be giving that error. Is there anything else that you may have configured incorrectly? Did you follow all instructions carefully from the documentation of my package?

**Comment by syed-reza98** [comment]
@andrewdwallo Yes, I have followed all the instructions carefully. I have created a fresh Laravel project. The artisan commands are:
1. composer require filament/filament:"^3.0-stable" -W
2. php artisan filament:install --panels
3. composer require andrewdwallo/filament-companies
4. php artisan filament-companies:install
5. php artisan migrate:fresh

After running the migration it shows:

   BadMethodCallException 

  Method Filament\Panel::getDomains does not exist.

  at vendor\filament\support\src\Concerns\Macroable.php:72
     68▕     {
     69▕         $macro = static::getMacro($method);
     70▕
     71▕         if ($macro === null) {
  ➜  72▕             throw new BadMethodCallException(sprintf(
     73▕                 'Method %s::%s does not exist.',
     74▕                 static::class,
     75▕                 $method,
     76▕             ));

  i   Bad Method Call: Did you mean Filament\Panel::getDomain() ?

  1   vendor\andrewdwallo\filament-companies\routes\web.php:22
      Filament\Support\Components\Component::__call("getDomains", [])

  2   vendor\laravel\framework\src\Illuminate\Routing\Router.php:502
      Illuminate\Support\ServiceProvider::{closure}(Object(Illuminate\Routing\Router))

**Comment by andrewdwallo** [comment]
@syed-reza98 I don't know what to tell you. I installed it and everything worked just fine. Try running `php artisan optimize:clear` and see if that changes anything. If all else fails, try reinstalling. I'm closing this issue as everything seems to be working on my end, and it also seems that this issue hasn't come across anyone else who has installed this package.
